### ISSUE TITLE
Application crashed when I wanted to sort results

### ISSUE THREAD

**Issue by hoverkw** [CMCSHE201/CheapShark_API_App#55]
I think this has been caused by the fact that application didn't load list of deals (I clicked earlier than list appeared on the scree). This looks like edge case which is not handled properly
Error contents below:
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: source
  Source=System.Linq
  StackTrace:
   at System.Linq.OrderedEnumerable`2..ctor(IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer, Boolean descending, OrderedEnumerable`1 parent)
   at System.Linq.Enumerable.OrderByDescending[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at csApiApp.Mvvm.Vm.DealsPageVm.SortByHighestPrice() in C:\!Moje\git\BeeliveryAcademy\T4app\CheapShark Project\csApiApp-master\csApiApp\csApiApp\Mvvm\Vm\DealsPageVm.cs:line 106
   at csApiApp.Mvvm.Vm.DealsPageVm.<get_SortDescCommand>b__8_0() in C:\!Moje\git\BeeliveryAcademy\T4app\CheapShark Project\csApiApp-master\csApiApp\csApiApp\Mvvm\Vm\DealsPageVm.cs:line 44
   at Xamarin.Forms.Command.<>c__DisplayClass4_0.<.ctor>b__0(Object o)
   at Xamarin.Forms.Command.Execute(Object parameter)
   at Xamarin.Forms.ButtonElement.ElementClicked(VisualElement visualElement, IButtonElement ButtonElementManager)
   at Xamarin.Forms.Button.SendClicked()
   at Xamarin.Forms.Platform.UWP.ButtonRenderer.OnButtonClick(Object sender, RoutedEventArgs e)

  This exception was originally thrown at this call stack:
    [External Code]
    csApiApp.Mvvm.Vm.DealsPageVm.SortByHighestPrice() in DealsPageVm.cs
    csApiApp.Mvvm.Vm.DealsPageVm.get_SortDescCommand.AnonymousMethod__8_0() in DealsPageVm.cs
    [External Code]

**Comment by CMCSHE201** [comment]
This issue has been fixed now. Validation has been added to stop the user sorting the results before the list is shown.
